import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";
import { Search_Book } from "./Search_Book";

export const metadata = {
  title: "From.",
  description: "Generated by FROM.",
};

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + `topics`, {
    cache: `no-store`,
  });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <Link href="/">
          <p class="home">From.</p>
        </Link>
        <object data="/line.svg" />
        <div class="container">
          <object data="/icon_1_comment.svg" type="image/svg+xml" />
          <div class="title_0">
            <div class="title_1">안녕하세요. 박소영님 </div>
            <div class="title_2">
              오늘은 기록
              {topics &&
                topics.map((topic) => {
                  return (
                    <article key={topic.id}>
                      <Link href={`/read/${topic.id}`}>{topic.id}</Link>
                    </article>
                  );
                })}
              번째 입니다.
            </div>
          </div>
        </div>
        <object data="/line.svg" />
        <Search_Book />
        {children}
        <Control />
        <ol>
          {topics &&
            topics.map((topic) => {
              return (
                <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                </li>
              );
            })}
        </ol>
      </body>
    </html>
  );
}
