import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";
import { Search_Book } from "./Search_Book";

export const metadata = {
  title: "From.",
  description: "Generated by FROM.",
};

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + `topics`, {
    cache: `no-store`,
  });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">
            <p class="text-[26px] text-center text-[#222]">From.</p>
          </Link>
        </h1>
        <object data="/line.svg" />
        <div class="container">
          {/* <object data="/icon_1_comment.svg" type="image/svg+xml" /> */}

          <svg
            width="26"
            height="26"
            viewBox="0 0 26 26"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            class="w-[26px] h-[26px]"
            preserveAspectRatio="none"
          >
            <path
              d="M16.25 10.5H9.75C9.33579 10.5 9 10.8358 9 11.25C9 11.6642 9.33579 12 9.75 12H16.25C16.6642 12 17 11.6642 17 11.25C17 10.8358 16.6642 10.5 16.25 10.5Z"
              fill="black"
            ></path>
            <path
              d="M13 22.4997C12.8802 22.499 12.7621 22.4695 12.656 22.4139C12.5499 22.3582 12.4586 22.2779 12.3899 22.1797C12.1699 21.8697 11.96 21.5497 11.76 21.2497C10.92 19.9597 10.3598 19.1097 8.82983 18.9797C7.57156 18.8868 6.35585 18.4849 5.29004 17.8097C4.28507 17.163 3.45764 16.2754 2.88306 15.2275C2.30847 14.1796 2.00492 13.0047 2 11.8097V10.5997C2.03159 8.67765 2.82412 6.8466 4.20386 5.5081C5.58359 4.16961 7.43775 3.43295 9.35986 3.45969H16.6499C18.5703 3.43562 20.422 4.17347 21.7996 5.51167C23.1771 6.84988 23.9684 8.6794 24 10.5997V11.8197C23.9951 13.0147 23.6915 14.1896 23.1169 15.2375C22.5424 16.2854 21.7149 17.173 20.71 17.8197C19.6442 18.4949 18.4282 18.8968 17.1699 18.9897C15.6399 19.1197 15.08 19.9897 14.24 21.2597C14.04 21.5597 13.8399 21.8797 13.6099 22.1897C13.5401 22.286 13.4484 22.3644 13.3423 22.4183C13.2362 22.4722 13.119 22.5001 13 22.4997ZM9.35986 4.99968C7.83555 4.97289 6.36285 5.5515 5.2644 6.6087C4.16596 7.66591 3.53153 9.11546 3.5 10.6397V11.8597C3.51295 12.7964 3.7581 13.7152 4.21362 14.5337C4.66915 15.3523 5.32068 16.045 6.10986 16.5497C6.96959 17.0895 7.9478 17.4121 8.95996 17.4897C11.21 17.6797 12.08 18.9997 12.96 20.4097C13.88 18.9997 14.76 17.6797 16.96 17.4897C17.9756 17.4137 18.9571 17.091 19.8198 16.5497C20.6065 16.0432 21.2558 15.3498 21.7095 14.5315C22.1631 13.7131 22.4072 12.7953 22.4199 11.8597V10.5997C22.391 9.07637 21.7587 7.6268 20.6619 6.56932C19.565 5.51184 18.0932 4.93292 16.5698 4.95969L9.35986 4.99968Z"
              fill="black"
            ></path>
          </svg>
          <div class="title_0">
            <div class="title_1">안녕하세요. 박소영님 </div>
            <div class="title_2">
              오늘은
              {topics &&
                topics.map((topic) => {
                  return (
                    <article key={topic.id}>
                      <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                    </article>
                  );
                })}
              번째 기록 입니다.
            </div>
          </div>
        </div>
        <object data="/line.svg" />
        <Search_Book />
        <object data="/line.svg" />
        <ol>
          {topics &&
            topics.map((topic) => {
              return (
                <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                </li>
              );
            })}
        </ol>
        {children}
        <object class="line_0" data="/line.svg" />
        <Control />
      </body>
    </html>
  );
}
